apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
    spec:
      containers:
      - name: socket-image
        image: gcr.io/macro-topic-406418/socket-image:47
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: socket-service
spec:
  selector:
    app: socket
  ports:
    - protocol: TCP
      port: 82
      targetPort: 5000
  type: LoadBalancer
  